services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aura
  redis:
      image: redis:7-alpine
      ports:
        - "6379:6379"
